### ISSUE TITLE
Install fails under node 4.2

### ISSUE THREAD

**Issue by febeling** [eHealthAfrica/grunt-angular-gettext-transifex#1]
The cause is eHealthAfrica/grunt-tx#7.

**Comment by rmehner** [comment]
Fixed in 1.1.1. You might need to get a current compiler on the system for Travis, see the travis.yml for this project:

``` yaml
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
```
